export const ELEMENT_PERMISSIONS = 'ELEMENT_PERMISSIONS';
export const COMPONENT_PERMISSIONS = 'COMPONENT_PERMISSIONS';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';
export const ERROR_POPUP = 'ERROR_POPUP';